spring:
    datasource:
        url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/pavliyk_3?serverTimezone=UTC}
        username: ${JDBC_DATABASE_USERNAME:lidl}
        password: ${JDBC_DATABASE_PASSWORD:CoolPassword233}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

#spring:
#    datasource:
#url:jdbc:mysql://localhost/pavliyk_3?serverTimezone=UTC
#username:lidl
#password:CoolPassword233
#driver-class-name:com.mysql.jdbc.Driver
#jpa:
## Show or not log for each sql query
#show-sql:true
#hibernate:
## Hibernate ddl auto (validate, create, create-drop, update)
#ddl-auto:create
## Naming strategy
#naming-strategy:org.hibernate.cfg.ImprovedNamingStrategy
#server:
#port:8080